### ISSUE TITLE
Every 12 hours print ticker that has the biggest change in tweets about it

### ISSUE THREAD

**Issue by TimKoornstra** [StephanAkkerman/FinTwit_Bot#25]
Both more and less
Eg $ETH from 100k tweets -> 120k tweets = 20% increase

**Comment by TimKoornstra** [comment]
all users (global sentiment)

**Comment by StephanAkkerman** [comment]
Maybe we can use https://docs.tweepy.org/en/stable/client.html#tweepy.Client.get_recent_tweets_count, from https://developer.twitter.com/en/docs/twitter-api/tweets/counts/introduction and run it against some tickers, we should be aware of the rate limit. We are not able to track all tickers or hashtags unfortunately. Maybe we could find a website that has trending tickers / hashtags and scrape that instead.

**Comment by StephanAkkerman** [comment]
We could also combine the global twitter sentiment with the users that we are following.
- #61

**Comment by StephanAkkerman** [comment]
Cannot do global sentiment, replaced by #158.
