### ISSUE TITLE
Show most important earning calls per week and day

### ISSUE THREAD

**Issue by TimKoornstra** [StephanAkkerman/FinTwit_Bot#35]

**Comment by StephanAkkerman** [comment]
Is there an API for doing this?
https://pypi.org/project/yahoo-earnings-calendar/

**Comment by StephanAkkerman** [comment]
Add channel 📅|earnings that posts weekly overview of the coming earnings, maybe post every friday after market close

**Comment by StephanAkkerman** [comment]
Also add a command to check the next earning date for a symbol `!earnings NVDA`

**Comment by StephanAkkerman** [comment]
> Add channel 📅|earnings that posts weekly overview of the coming earnings, maybe post every friday after market close.

There are already 80+ earnings today. If we post all weekly embeds this is going to be at least 300 rows of data. We could choose to filter it based on market cap or volume?
